server:
  port: 8090
spring:
  data:
    mongodb:
      username: alibou
      password: alibou
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 500ms
  rate-limiter:
    instances:
      myRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 500ms
  circuitbreaker:
    instances:
      customermicroService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
